/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datnd.view;

import datnd.daos.PhoneDAO;
import datnd.daos.UserDAO;
import duydat.dtos.PhoneDTO;
import duydat.dtos.UserDTO;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Dat
 */
public class AdminFrame extends javax.swing.JFrame {

    private String username;
    private DefaultTableModel model=null;
    private BufferedImage currentImage = null;
    private Graphics g= null;
    private int x=5, y=10;
    private String linkImage;
    JFileChooser fChooser = new JFileChooser();
    int row;
    List<PhoneDTO> list;
    /**
     * Creates new form AdminFrame
     */
    
    //default constructor
    public AdminFrame() {
        initComponents();
    }

    //constructor to initialize the frame after login
    public AdminFrame(String username, String role) {
        initComponents();
        //show user's username and role on the top of the frame
        this.username=username;
        this.lblRole.setText(username+" - "+role);
        //get model of the view table
        model=(DefaultTableModel) tblView.getModel();
        //show all phones detail on the view table
        loadAllPhones();
        //get graphic
        g= this.pnlImage.getGraphics();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files","GIF","JPG","JPEG","PNG");
        fChooser.setFileFilter(filter);
        //show all information of that user
        loadProfile();
        //set line wrap for the jtextarea that contains descriptions of phones
        txtShowDescription.setWrapStyleWord(true);
        txtShowDescription.setLineWrap(true);
        txtUpdateDescription.setWrapStyleWord(true);
        txtUpdateDescription.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblRole = new javax.swing.JLabel();
        tabMenu = new javax.swing.JTabbedPane();
        pnlAllPhone = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        pnlPhoneDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtShowPhoneID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShowPhonename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShowDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtShowPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtShowMaker = new javax.swing.JTextField();
        pnlImage = new javax.swing.JPanel();
        txtFailedImage = new javax.swing.JLabel();
        rbShowIsDisabled = new javax.swing.JRadioButton();
        pnlInsertPhone = new javax.swing.JPanel();
        pnlPhoneDetail1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtInsertPhoneID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtInsertPhonename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInsertDescription = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtInsertPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtInsertMaker = new javax.swing.JTextField();
        btnInsertImage = new javax.swing.JButton();
        txtInsertImage = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlUpdatePhone = new javax.swing.JPanel();
        pnlPhoneDetail2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtUpdatePhoneID = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtUpdatePhonename = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtUpdateDescription = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        txtUpdatePrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtUpdateMaker = new javax.swing.JTextField();
        btnUpdateImage = new javax.swing.JButton();
        txtUpdateImage = new javax.swing.JTextField();
        btnUpdateCheck = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnUpdateReset = new javax.swing.JButton();
        pnlDisablePhone = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtDeletePhoneID = new javax.swing.JTextField();
        btnDisablePhone = new javax.swing.JButton();
        btnEnablePhone = new javax.swing.JButton();
        pnlUpdateProfile = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUpdateUsername = new javax.swing.JTextField();
        txtUpdatePassword = new javax.swing.JPasswordField();
        txtUpdateFullname = new javax.swing.JTextField();
        rbAdmin = new javax.swing.JRadioButton();
        rbUser = new javax.swing.JRadioButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblRole.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRole.setText("jLabel1");

        tabMenu.setBackground(new java.awt.Color(255, 255, 255));

        pnlAllPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAllPhoneMouseExited(evt);
            }
        });

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PhoneID", "Maker", "Phonename", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);
        if (tblView.getColumnModel().getColumnCount() > 0) {
            tblView.getColumnModel().getColumn(3).setHeaderValue("Description");
        }

        pnlPhoneDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone details"));

        jLabel1.setText("Phone ID:");

        jLabel2.setText("Phonename:");

        jLabel3.setText("Description:");

        txtShowDescription.setColumns(20);
        txtShowDescription.setRows(5);
        jScrollPane2.setViewportView(txtShowDescription);

        jLabel4.setText("Price:");

        jLabel5.setText("Maker:");

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFailedImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFailedImage)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        rbShowIsDisabled.setText("is Disabled");

        javax.swing.GroupLayout pnlPhoneDetailLayout = new javax.swing.GroupLayout(pnlPhoneDetail);
        pnlPhoneDetail.setLayout(pnlPhoneDetailLayout);
        pnlPhoneDetailLayout.setHorizontalGroup(
            pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhoneDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtShowPrice)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtShowPhonename)
                            .addComponent(txtShowMaker)
                            .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                                .addComponent(txtShowPhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbShowIsDisabled)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        pnlPhoneDetailLayout.setVerticalGroup(
            pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowPhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbShowIsDisabled))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowPhonename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlAllPhoneLayout = new javax.swing.GroupLayout(pnlAllPhone);
        pnlAllPhone.setLayout(pnlAllPhoneLayout);
        pnlAllPhoneLayout.setHorizontalGroup(
            pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPhoneDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlAllPhoneLayout.setVerticalGroup(
            pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPhoneDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        tabMenu.addTab("Show All Phones", pnlAllPhone);

        pnlInsertPhone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPhoneDetail1.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone details"));

        jLabel6.setText("Phone ID:");

        jLabel7.setText("Phonename:");

        jLabel8.setText("Description:");

        txtInsertDescription.setColumns(20);
        txtInsertDescription.setRows(5);
        jScrollPane3.setViewportView(txtInsertDescription);

        jLabel9.setText("Price:");

        jLabel10.setText("Maker:");

        btnInsertImage.setText("Choose Image");
        btnInsertImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPhoneDetail1Layout = new javax.swing.GroupLayout(pnlPhoneDetail1);
        pnlPhoneDetail1.setLayout(pnlPhoneDetail1Layout);
        pnlPhoneDetail1Layout.setHorizontalGroup(
            pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertImage))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhoneDetail1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInsertPrice)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(txtInsertPhonename)
                    .addComponent(txtInsertPhoneID)
                    .addComponent(txtInsertMaker)
                    .addComponent(txtInsertImage))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlPhoneDetail1Layout.setVerticalGroup(
            pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertPhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertPhonename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertImage)
                    .addComponent(txtInsertImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pnlInsertPhone.add(pnlPhoneDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 530, -1));

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        pnlInsertPhone.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 310, -1));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        pnlInsertPhone.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 310, -1));

        tabMenu.addTab(" Insert Phone", pnlInsertPhone);
        pnlInsertPhone.getAccessibleContext().setAccessibleName("");

        pnlUpdatePhone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPhoneDetail2.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone details"));

        jLabel12.setText("Phone ID:");

        jLabel13.setText("Phonename:");

        jLabel14.setText("Description:");

        txtUpdateDescription.setColumns(20);
        txtUpdateDescription.setRows(5);
        jScrollPane4.setViewportView(txtUpdateDescription);

        jLabel15.setText("Price:");

        jLabel16.setText("Maker:");

        btnUpdateImage.setText("Choose Image");
        btnUpdateImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateImageActionPerformed(evt);
            }
        });

        btnUpdateCheck.setText("Check Information");
        btnUpdateCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPhoneDetail2Layout = new javax.swing.GroupLayout(pnlPhoneDetail2);
        pnlPhoneDetail2.setLayout(pnlPhoneDetail2Layout);
        pnlPhoneDetail2Layout.setHorizontalGroup(
            pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateImage, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhoneDetail2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                        .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUpdatePrice)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtUpdatePhonename)
                            .addComponent(txtUpdateMaker)
                            .addComponent(txtUpdateImage))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                        .addComponent(txtUpdatePhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlPhoneDetail2Layout.setVerticalGroup(
            pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdatePhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdatePhonename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdateMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPhoneDetail2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(pnlPhoneDetail2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateImage)
                    .addComponent(txtUpdateImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        pnlUpdatePhone.add(pnlPhoneDetail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 107, -1, -1));

        jLabel11.setText("To update information of a phone, you need to know the phoneID");
        pnlUpdatePhone.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 22, 588, -1));

        jLabel18.setText("NOTE: PhoneID musn't be changed");
        pnlUpdatePhone.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 45, 588, -1));

        jLabel19.setText("Fill in the fields of information you need to change");
        pnlUpdatePhone.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 68, -1, -1));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        pnlUpdatePhone.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 156, 274, -1));

        btnUpdateReset.setText("Reset");
        btnUpdateReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateResetActionPerformed(evt);
            }
        });
        pnlUpdatePhone.add(btnUpdateReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 337, 274, -1));

        tabMenu.addTab("Update Phone's information", pnlUpdatePhone);

        pnlDisablePhone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("PhoneID to Disable or Enable:");
        pnlDisablePhone.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 37, 210, 20));
        pnlDisablePhone.add(txtDeletePhoneID, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 38, 369, -1));

        btnDisablePhone.setBackground(new java.awt.Color(255, 102, 102));
        btnDisablePhone.setForeground(new java.awt.Color(255, 255, 255));
        btnDisablePhone.setText("Disable");
        btnDisablePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisablePhoneActionPerformed(evt);
            }
        });
        pnlDisablePhone.add(btnDisablePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 144, -1));

        btnEnablePhone.setBackground(new java.awt.Color(51, 102, 255));
        btnEnablePhone.setForeground(new java.awt.Color(255, 255, 255));
        btnEnablePhone.setText("Enable");
        btnEnablePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnablePhoneActionPerformed(evt);
            }
        });
        pnlDisablePhone.add(btnEnablePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 120, -1));

        tabMenu.addTab("Disable/Enable", pnlDisablePhone);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Profile:");

        jLabel21.setText("Username:");

        jLabel22.setText("Password:");

        jLabel23.setText("Fullname:");

        jLabel24.setText("Role:");

        buttonGroup1.add(rbAdmin);
        rbAdmin.setText("admin");

        buttonGroup1.add(rbUser);
        rbUser.setText("user");

        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbAdmin)
                        .addGap(62, 62, 62)
                        .addComponent(rbUser)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUpdateUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txtUpdatePassword)
                            .addComponent(btnUpdateProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateFullname))
                        .addGap(0, 41, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtUpdateFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rbAdmin)
                    .addComponent(rbUser))
                .addGap(71, 71, 71)
                .addComponent(btnUpdateProfile)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUpdateProfileLayout = new javax.swing.GroupLayout(pnlUpdateProfile);
        pnlUpdateProfile.setLayout(pnlUpdateProfileLayout);
        pnlUpdateProfileLayout.setHorizontalGroup(
            pnlUpdateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        pnlUpdateProfileLayout.setVerticalGroup(
            pnlUpdateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        tabMenu.addTab("Update Profile", pnlUpdateProfile);

        btnLogOut.setText("Log out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabMenu)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tabMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(21, 21, 21))
        );

        tabMenu.getAccessibleContext().setAccessibleName("Insert");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //load all phones in the database (both available and disabled) on to the table
    private void loadAllPhones(){
        model.setRowCount(0);
        PhoneDAO dao=new PhoneDAO();
        try {
            list= dao.loadAllPhones(1);
            List<PhoneDTO> listOfDisable= dao.loadAllPhones(0);
            list.addAll(listOfDisable);
            for(PhoneDTO dto:list)
                model.addRow(dto.toVector());
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error when loading data!");
        } 
    }
    
    //method to draw an image with the link 
    private void showImage(String imageLink) throws Exception{
            txtFailedImage.setText("");
            currentImage=ImageIO.read(new File(imageLink));
            if(currentImage!=null){
                //delete the old picture
                g.clearRect(x, y,pnlImage.getWidth()-x,pnlImage.getHeight()-y);
                //get size of the picture to draw
                int imgWidth = currentImage.getWidth();
                int imgHeight = currentImage.getHeight();
                double ratio = 1.0*imgWidth/imgHeight;
                int areaWidth = this.pnlImage.getWidth()-2*x;
                int areaHeight = this.pnlImage.getHeight()-2*y;
                //if the image is smaller than panel to draw --> make the panel smaller
                if(imgWidth<=areaWidth && imgHeight <=areaHeight){
                    areaHeight=imgHeight;
                    areaWidth=imgWidth;
                }else if(imgWidth>imgHeight){ 
                    if(imgWidth<areaWidth) areaWidth = imgWidth;
                    areaHeight = (int) (areaWidth/ratio);
                }else{
                    if(imgHeight<areaHeight)areaHeight = imgHeight;
                    areaWidth=(int) (areaHeight*ratio);
                }
                //after adjust the image and panel, draw picture
                g.drawImage(currentImage, x, y,areaWidth,areaHeight,this.pnlImage);
            }
    }
    
    //when button "Log out" is pressed, finish the work frame, open login frame
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    //when admin click on a row in the table, show the detail
    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        row=tblView.getSelectedRow();
        if(row<-1)
            return;
        String phoneID=(String) tblView.getValueAt(row, 0);
        txtShowPhoneID.setText(phoneID);
        if(!list.get(row).isAvailable())
            rbShowIsDisabled.setSelected(true);
        else
            rbShowIsDisabled.setSelected(false);
        txtShowMaker.setText((String) tblView.getValueAt(row, 1));
        txtShowPhonename.setText((String) tblView.getValueAt(row, 2));
        txtShowDescription.setText((String) tblView.getValueAt(row, 3));
        txtShowPrice.setText(tblView.getValueAt(row, 4).toString());
        PhoneDAO dao=new PhoneDAO();
        try {
            linkImage = dao.getLinkImage(phoneID);
            if(linkImage!=null)
                showImage(linkImage);
            else 
                txtFailedImage.setText("Cannot show image!");
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            txtFailedImage.setText("Cannot show image!");
        }
    }//GEN-LAST:event_tblViewMouseClicked

    //clear all information in the Insert panel
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtInsertDescription.setText("");
        txtInsertMaker.setText("");
        txtInsertPhoneID.setText("");
        txtInsertPhonename.setText("");
        txtInsertPrice.setText("");
        txtInsertImage.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    //choose link of image by JFileChooser
    private void btnInsertImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertImageActionPerformed
        try {
            int result= fChooser.showOpenDialog(this);
            if(result==JFileChooser.APPROVE_OPTION)
            {
                File f= fChooser.getSelectedFile();
                if(f.isFile())
                {
                    String image=f.getAbsolutePath();
                    txtInsertImage.setText(image);
                }
            }
        } catch (Exception e) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnInsertImageActionPerformed

    //check that no information is null
    private boolean validateInfor(String phoneID,String phonename,String maker,String description, String price, String image){
        boolean result=true;
        if(phoneID.length()==0|| phonename.length()==0||
           maker.length()==0|| description.length()==0||
                image.length()==0||price.length()==0)
        {
            result=false;
            JOptionPane.showMessageDialog(this, "Information must not be blank");
        }
        return result;
    }
    
    //insert a new phone into Phones table
    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try{
            String phoneID= txtInsertPhoneID.getText();
            String phonename=txtInsertPhonename.getText();
            String maker=txtInsertMaker.getText();
            String description=txtInsertDescription.getText();
            String txtprice=txtInsertPrice.getText();
            String image=txtInsertImage.getText();
            if(!validateInfor(phoneID, phonename, maker, description, txtprice, image)){
                return;
            }
            int price=Integer.parseInt(txtprice);
            PhoneDTO dto=new PhoneDTO(phoneID, phonename, maker, description, image, price);
            PhoneDAO dao=new PhoneDAO();
            boolean result=dao.insertPhone(dto);
            if(result)
            {
                JOptionPane.showMessageDialog(this, "Successfull");
                model.addRow(dto.toVector());
                this.tabMenu.setSelectedIndex(0);
                this.tblView.setRowSelectionInterval(tblView.getRowCount()-1, tblView.getRowCount()-1);
            }
            else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }
        catch(Exception e)
        {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, e);
            if(e.getMessage().contains("duplicate")){
                JOptionPane.showMessageDialog(this, "PhoneID has existed");
                txtInsertPhoneID.setFocusable(true);
            }
            else{
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    //choose link of image by JFileChooser
    private void btnUpdateImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateImageActionPerformed
        try {
            int result= fChooser.showOpenDialog(this);
            if(result==JFileChooser.APPROVE_OPTION)
            {
                File f= fChooser.getSelectedFile();
                if(f.isFile())
                {
                    String image=f.getAbsolutePath();
                    txtUpdateImage.setText(image);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_btnUpdateImageActionPerformed

    //clear all information in the Update panel
    private void btnUpdateResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateResetActionPerformed
        txtUpdatePhoneID.setText("");
        txtUpdatePhoneID.setEditable(true);
        txtUpdateDescription.setText("");
        txtUpdateImage.setText("");
        txtUpdateMaker.setText("");
        txtUpdatePhonename.setText("");
        txtUpdatePrice.setText("");
    }//GEN-LAST:event_btnUpdateResetActionPerformed

    //update phone's information
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            String phoneID=txtUpdatePhoneID.getText();
            PhoneDAO dao= new PhoneDAO();
            boolean check=dao.isPhoneIDExisted(phoneID);
            if(!check){
                JOptionPane.showMessageDialog(this, "PhoneID doesn't exist");
                return;
            }
            String phonename=txtUpdatePhonename.getText();
            String maker=txtUpdateMaker.getText();
            String description=txtUpdateDescription.getText();
            String txtprice=txtUpdatePrice.getText();
            String image=txtUpdateImage.getText();
            boolean result=dao.updatePhoneInformation(phoneID, phonename, maker, description, txtprice, image);
            if(result)
            {
                JOptionPane.showMessageDialog(this, "Successfull");
                loadAllPhones();
                this.tabMenu.setSelectedIndex(0);
                this.tblView.setRowSelectionInterval(tblView.getRowCount()-1, tblView.getRowCount()-1);
            }
            else{
                JOptionPane.showMessageDialog(this, "Failed");
            }
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    //load profile of the user
    private void loadProfile(){
        UserDAO dao= new UserDAO();
        try {
            UserDTO dto=dao.searchByUsername(username);
            txtUpdateUsername.setText(username);
            txtUpdateUsername.setEditable(false);
            txtUpdateFullname.setText(dto.getFullname());
            txtUpdatePassword.setText(dto.getPassword());
            if(dto.getRole().equals("admin"))
                rbAdmin.setSelected(true);
            else
                rbUser.setSelected(true);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error when loading profile of "+ username);
        }
        
    }
    
    //make a phone disabled
    private void btnDisablePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisablePhoneActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Are you sure to disable this phone? ") != JOptionPane.YES_OPTION)
            return;
        String phoneID=txtDeletePhoneID.getText();
        if(phoneID.length()==0)
        {
            JOptionPane.showMessageDialog(null, "PhoneID is not null");
            return;
        }
        try {
            PhoneDAO dao= new PhoneDAO();
            boolean checkID=dao.isPhoneIDExisted(phoneID);
            if(checkID){
                boolean result=dao.disablePhone(phoneID);
                if(result)
                {
                    JOptionPane.showMessageDialog(this, "Successfull");
                    loadAllPhones();
                    this.tabMenu.setSelectedIndex(0);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "This PhoneID doesn't exist!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed");
        }
        
    }//GEN-LAST:event_btnDisablePhoneActionPerformed

    //update profile of the user
    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        String password=new String(txtUpdatePassword.getPassword());
        String fullname=txtUpdateFullname.getText();
        String role;
        if(rbAdmin.isSelected())
            role="admin";
        else
            role="user";
        UserDTO dto= new UserDTO(username, fullname, role, password);
        UserDAO dao=new UserDAO();
        try {
            boolean result=dao.updateUserProfile(dto);
            if(result)
            {
                JOptionPane.showMessageDialog(null, "Updated successfully!");
                if(role.equals("user")){
                    JOptionPane.showMessageDialog(this, "Your role is changed, login again and continue your work!");
                    this.dispose();
                    new LoginJFrame().setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Updated Failed!");
            }    
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed");
        }
        
    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    private void pnlAllPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllPhoneMouseExited
        try {
            if(linkImage!=null)
                showImage(linkImage);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlAllPhoneMouseExited

    //show information of the phone before updating
    private void btnUpdateCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCheckActionPerformed
        String phoneID=this.txtUpdatePhoneID.getText();
        PhoneDAO dao= new PhoneDAO();
        PhoneDTO dto;
        try {
            dto = dao.searchByPhoneID(phoneID);
            if(dto==null){
                JOptionPane.showMessageDialog(this, "The phone ID doesn't exist");
            }
            else{
                this.txtUpdatePhoneID.setEditable(false);
                this.txtUpdatePhonename.setText(dto.getPhonename());
                this.txtUpdateDescription.setText(dto.getDescription());
                this.txtUpdateMaker.setText(dto.getMaker());
                this.txtUpdateImage.setText(dto.getLink());
                this.txtUpdatePrice.setText(dto.getPrice()+"");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateCheckActionPerformed

    //method to enable a phone
    private void btnEnablePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnablePhoneActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Are you sure to enable this phone? ") != JOptionPane.YES_OPTION)
            return;
        String phoneID=txtDeletePhoneID.getText();
        if(phoneID.length()==0)
        {
            JOptionPane.showMessageDialog(null, "PhoneID is not null");
            return;
        }
        try {
            PhoneDAO dao= new PhoneDAO();
            boolean checkID=dao.isPhoneIDExisted(phoneID);
            if(checkID){
                boolean result=dao.enablePhone(phoneID);
                if(result)
                {
                    JOptionPane.showMessageDialog(this, "Successfull");
                    loadAllPhones();
                    this.tabMenu.setSelectedIndex(0);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "This PhoneID doesn't exist!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_btnEnablePhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisablePhone;
    private javax.swing.JButton btnEnablePhone;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnInsertImage;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateCheck;
    private javax.swing.JButton btnUpdateImage;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.JButton btnUpdateReset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel pnlAllPhone;
    private javax.swing.JPanel pnlDisablePhone;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlInsertPhone;
    private javax.swing.JPanel pnlPhoneDetail;
    private javax.swing.JPanel pnlPhoneDetail1;
    private javax.swing.JPanel pnlPhoneDetail2;
    private javax.swing.JPanel pnlUpdatePhone;
    private javax.swing.JPanel pnlUpdateProfile;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbShowIsDisabled;
    private javax.swing.JRadioButton rbUser;
    private javax.swing.JTabbedPane tabMenu;
    private javax.swing.JTable tblView;
    private javax.swing.JTextField txtDeletePhoneID;
    private javax.swing.JLabel txtFailedImage;
    private javax.swing.JTextArea txtInsertDescription;
    private javax.swing.JTextField txtInsertImage;
    private javax.swing.JTextField txtInsertMaker;
    private javax.swing.JTextField txtInsertPhoneID;
    private javax.swing.JTextField txtInsertPhonename;
    private javax.swing.JTextField txtInsertPrice;
    private javax.swing.JTextArea txtShowDescription;
    private javax.swing.JTextField txtShowMaker;
    private javax.swing.JTextField txtShowPhoneID;
    private javax.swing.JTextField txtShowPhonename;
    private javax.swing.JTextField txtShowPrice;
    private javax.swing.JTextArea txtUpdateDescription;
    private javax.swing.JTextField txtUpdateFullname;
    private javax.swing.JTextField txtUpdateImage;
    private javax.swing.JTextField txtUpdateMaker;
    private javax.swing.JPasswordField txtUpdatePassword;
    private javax.swing.JTextField txtUpdatePhoneID;
    private javax.swing.JTextField txtUpdatePhonename;
    private javax.swing.JTextField txtUpdatePrice;
    private javax.swing.JTextField txtUpdateUsername;
    // End of variables declaration//GEN-END:variables
}
