/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datnd.view;

import datnd.daos.PhoneDAO;
import datnd.daos.UserDAO;
import duydat.dtos.PhoneDTO;
import duydat.dtos.UserDTO;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Dat
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    private String username;
    private DefaultTableModel model=null;
    private DefaultTableModel searchModel=null;
    private BufferedImage currentImage = null;
    private Graphics g= null;
    private Graphics searchG= null;
    private int x=5, y=10;
    String linkImage;
    String linkSearchImage;
    
    //default constructor
    public UserFrame() {
        initComponents();
        this.lblRole.setText("");
    }
    
    //constructor to initialize the frame after login
    public UserFrame(String username,String role) {
        initComponents();
        //show user's username and role on the top of the frame
        this.lblRole.setText(username+" - "+role);
        this.username=username;
        //get model of the view table
        model=(DefaultTableModel) tblView.getModel();
        searchModel=(DefaultTableModel) tblSearchResult.getModel();
        //show all phones detail on the view table
        loadAllPhones();
        //get graphic
        g= this.pnlImage.getGraphics();
        searchG=this.pnlSearchImage.getGraphics();
        //show all information of that user
        loadProfile();
        //set line wrap for the jtextarea that contains descriptions of phones
        txtShowDescription.setWrapStyleWord(true);
        txtShowDescription.setLineWrap(true);
        txtSearchDescription.setWrapStyleWord(true);
        txtSearchDescription.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblRole = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlAllPhone = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblView = new javax.swing.JTable();
        pnlPhoneDetail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtShowPhoneID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtShowPhonename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtShowDescription = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtShowPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtShowMaker = new javax.swing.JTextField();
        pnlImage = new javax.swing.JPanel();
        txtFailImage = new javax.swing.JLabel();
        pnlSearchPhone = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPhonename = new javax.swing.JTextField();
        txtMaker = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFromPrice = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtToPrice = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        pnlPhoneDetail1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSearchPhoneID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSearchPhonename = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSearchDescription = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtSearchPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSearchMaker = new javax.swing.JTextField();
        pnlSearchImage = new javax.swing.JPanel();
        txtSearchFailImage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSearchResult = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        lbCountResult = new javax.swing.JLabel();
        pnlUpdateProfile = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtUpdateUsername = new javax.swing.JTextField();
        txtUpdatePassword = new javax.swing.JPasswordField();
        txtUpdateFullname = new javax.swing.JTextField();
        rbAdmin = new javax.swing.JRadioButton();
        rbUser = new javax.swing.JRadioButton();
        btnUpdateProfile = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblRole.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblRole.setText("jLabel1");

        pnlAllPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlAllPhoneMouseExited(evt);
            }
        });

        tblView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PhoneID", "Maker", "Phonename", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblView);

        pnlPhoneDetail.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone details"));

        jLabel1.setText("Phone ID:");

        jLabel2.setText("Phonename:");

        jLabel3.setText("Description:");

        txtShowDescription.setColumns(20);
        txtShowDescription.setRows(5);
        jScrollPane2.setViewportView(txtShowDescription);

        jLabel4.setText("Price:");

        jLabel5.setText("Maker:");

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFailImage)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFailImage)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPhoneDetailLayout = new javax.swing.GroupLayout(pnlPhoneDetail);
        pnlPhoneDetail.setLayout(pnlPhoneDetailLayout);
        pnlPhoneDetailLayout.setHorizontalGroup(
            pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhoneDetailLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtShowPrice)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                    .addComponent(txtShowPhonename)
                    .addComponent(txtShowPhoneID)
                    .addComponent(txtShowMaker))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlPhoneDetailLayout.setVerticalGroup(
            pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowPhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowPhonename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPhoneDetailLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtShowPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlAllPhoneLayout = new javax.swing.GroupLayout(pnlAllPhone);
        pnlAllPhone.setLayout(pnlAllPhoneLayout);
        pnlAllPhoneLayout.setHorizontalGroup(
            pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(pnlPhoneDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAllPhoneLayout.setVerticalGroup(
            pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAllPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPhoneDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Show all Phones", pnlAllPhone);

        pnlSearchPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSearchPhoneMouseExited(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel12.setText("By Phonename:");

        jLabel13.setText("By Maker:");

        jLabel14.setText("By Price:");

        jLabel15.setText("from");

        jLabel16.setText("to");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhonename, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(txtMaker))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFromPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)
                        .addGap(219, 219, 219))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtToPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPhonename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(txtFromPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(txtToPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnReset))
                .addContainerGap())
        );

        pnlPhoneDetail1.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone details"));

        jLabel6.setText("Phone ID:");

        jLabel7.setText("Phonename:");

        jLabel8.setText("Description:");

        txtSearchDescription.setColumns(20);
        txtSearchDescription.setRows(5);
        jScrollPane3.setViewportView(txtSearchDescription);

        jLabel9.setText("Price:");

        jLabel10.setText("Maker:");

        javax.swing.GroupLayout pnlSearchImageLayout = new javax.swing.GroupLayout(pnlSearchImage);
        pnlSearchImage.setLayout(pnlSearchImageLayout);
        pnlSearchImageLayout.setHorizontalGroup(
            pnlSearchImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchFailImage)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        pnlSearchImageLayout.setVerticalGroup(
            pnlSearchImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchFailImage)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPhoneDetail1Layout = new javax.swing.GroupLayout(pnlPhoneDetail1);
        pnlPhoneDetail1.setLayout(pnlPhoneDetail1Layout);
        pnlPhoneDetail1Layout.setHorizontalGroup(
            pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlSearchImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPhoneDetail1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchPrice)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                            .addComponent(txtSearchPhonename)
                            .addComponent(txtSearchPhoneID)
                            .addComponent(txtSearchMaker))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlPhoneDetail1Layout.setVerticalGroup(
            pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchPhoneID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPhonename, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchMaker, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPhoneDetail1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPhoneDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSearchImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblSearchResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PhoneID", "Maker", "Phonename", "Description", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSearchResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchResultMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSearchResult);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Result:");

        lbCountResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout pnlSearchPhoneLayout = new javax.swing.GroupLayout(pnlSearchPhone);
        pnlSearchPhone.setLayout(pnlSearchPhoneLayout);
        pnlSearchPhoneLayout.setHorizontalGroup(
            pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSearchPhoneLayout.createSequentialGroup()
                        .addGroup(pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSearchPhoneLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(lbCountResult)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(pnlPhoneDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        pnlSearchPhoneLayout.setVerticalGroup(
            pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPhoneDetail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSearchPhoneLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSearchPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCountResult)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Phone", pnlSearchPhone);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Profile:");

        jLabel21.setText("Username:");

        jLabel22.setText("Password:");

        jLabel23.setText("Fullname:");

        jLabel24.setText("Role:");

        buttonGroup1.add(rbAdmin);
        rbAdmin.setText("admin");

        buttonGroup1.add(rbUser);
        rbUser.setText("user");

        btnUpdateProfile.setText("Update Profile");
        btnUpdateProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbAdmin)
                        .addGap(62, 62, 62)
                        .addComponent(rbUser)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtUpdateUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txtUpdatePassword)
                            .addComponent(btnUpdateProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUpdateFullname))
                        .addGap(0, 41, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUpdatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtUpdateFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(rbAdmin)
                    .addComponent(rbUser))
                .addGap(92, 92, 92)
                .addComponent(btnUpdateProfile)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlUpdateProfileLayout = new javax.swing.GroupLayout(pnlUpdateProfile);
        pnlUpdateProfile.setLayout(pnlUpdateProfileLayout);
        pnlUpdateProfileLayout.setHorizontalGroup(
            pnlUpdateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        pnlUpdateProfileLayout.setVerticalGroup(
            pnlUpdateProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUpdateProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("Update Profile", pnlUpdateProfile);

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //when button "Log out" is pressed, finish the work frame, open login frame
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    //load profile of the user
    private void loadProfile(){
        UserDAO dao= new UserDAO();
        try {
            UserDTO dto=dao.searchByUsername(username);
            txtUpdateUsername.setText(username);
            txtUpdateUsername.setEditable(false);
            txtUpdateFullname.setText(dto.getFullname());
            txtUpdatePassword.setText(dto.getPassword());
            if(dto.getRole().equals("admin"))
                rbAdmin.setSelected(true);
            else
                rbUser.setSelected(true);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error when loading profile of "+ username);
        }
        
    }
    
    //load all phones in the database (only available) on to the table
    private void loadAllPhones(){
        PhoneDAO dao=new PhoneDAO();
        try {
            List<PhoneDTO> list= dao.loadAllPhones(1);
            for(PhoneDTO dto:list)
                model.addRow(dto.toVector());
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Error when loading the data");
        } 
    }
    
    //method to draw an image with the link 
    private void showImage(String imageLink, Graphics g) throws Exception{
            txtFailImage.setText("");
            txtSearchFailImage.setText("");
            currentImage=ImageIO.read(new File(imageLink));
            if(currentImage!=null){
                //delete the old picture
                g.clearRect(x, y,pnlImage.getWidth()-x,pnlImage.getHeight()-y);
                //get size of the picture to draw
                int imgWidth = currentImage.getWidth();
                int imgHeight = currentImage.getHeight();
                double ratio = 1.0*imgWidth/imgHeight;
                int areaWidth = this.pnlImage.getWidth()-2*x;
                int areaHeight = this.pnlImage.getHeight()-2*y;
                //if the image is smaller than panel to draw --> make the panel smaller
                if(imgWidth<=areaWidth && imgHeight <=areaHeight){
                    areaHeight=imgHeight;
                    areaWidth=imgWidth;
                }else if(imgWidth>imgHeight){
                    if(imgWidth<areaWidth) areaWidth = imgWidth;
                    areaHeight = (int) (areaWidth/ratio);
                }else{
                    if(imgHeight<areaHeight)areaHeight = imgHeight;
                    areaWidth=(int) (areaHeight*ratio);
                }
                //after adjust the image and panel, draw picture
                g.drawImage(currentImage, x, y,areaWidth,areaHeight,this.pnlImage);
            }
    }
    
    //when user click on a row in the table, show the detail
    private void tblViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewMouseClicked
        int row=tblView.getSelectedRow();
        String phoneID=(String) tblView.getValueAt(row, 0);
        txtShowPhoneID.setText(phoneID);
        txtShowMaker.setText((String) tblView.getValueAt(row, 1));
        txtShowPhonename.setText((String) tblView.getValueAt(row, 2));
        txtShowDescription.setText((String) tblView.getValueAt(row, 3));
        txtShowPrice.setText(tblView.getValueAt(row, 4).toString());
        PhoneDAO dao=new PhoneDAO();
        
        try {
            linkImage = dao.getLinkImage(phoneID);
            if(linkImage!=null)
                showImage(linkImage,g);
            else
            {
                txtFailImage.setText("Cannot show image!");
                txtSearchFailImage.setText("Cannot show image!");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            txtFailImage.setText("Cannot show image!");
            txtSearchFailImage.setText("Cannot show image!");
        }

    }//GEN-LAST:event_tblViewMouseClicked

    //update profile of the user
    private void btnUpdateProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateProfileActionPerformed
        String password=new String(txtUpdatePassword.getPassword());
        String fullname=txtUpdateFullname.getText();
        String role;
        if(rbAdmin.isSelected())
            role="admin";
        else
            role="user";
        UserDTO dto= new UserDTO(username, fullname, role, password);
        UserDAO dao=new UserDAO();
        try {
            boolean result=dao.updateUserProfile(dto);
            if(result)
            {
                JOptionPane.showMessageDialog(this, "Updated successfully!");
                if(role.equals("admin")){
                    JOptionPane.showMessageDialog(this, "Your role is changed, login again and continue your work!");
                    this.dispose();
                    new LoginJFrame().setVisible(true);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Updated Failed!");
            }
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed");
        }

    }//GEN-LAST:event_btnUpdateProfileActionPerformed

    //when user click on a row in the table, show the detail
    private void tblSearchResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchResultMouseClicked
        int row=tblSearchResult.getSelectedRow();
        String phoneID=(String) tblSearchResult.getValueAt(row, 0);
        txtSearchPhoneID.setText(phoneID);
        txtSearchMaker.setText((String) tblSearchResult.getValueAt(row, 1));
        txtSearchPhonename.setText((String) tblSearchResult.getValueAt(row, 2));
        txtSearchDescription.setText((String) tblSearchResult.getValueAt(row, 3));
        txtSearchPrice.setText(tblSearchResult.getValueAt(row, 4).toString());
        PhoneDAO dao=new PhoneDAO();
        try {
            linkSearchImage = dao.getLinkImage(phoneID);
            showImage(linkSearchImage,searchG);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblSearchResultMouseClicked

    //search phones based on inputed information
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        try {
            String phonename=txtPhonename.getText();
            String maker=txtMaker.getText();
            String from=txtFromPrice.getText();
            String to=txtToPrice.getText();
            List<PhoneDTO> result=null;
            PhoneDAO dao=new PhoneDAO();
            if(phonename.length()!=0)
                result=dao.searchByPhonename(phonename);
            else if(maker.length()!=0)
                result=dao.searchByMaker(maker);
            else if(from.length()!=0&&to.length()==0)
            {
                //set 'to' to an infinite number
                to="1000000000";
                result=dao.searchByPrice(from, to);
            }
            else if(from.length()==0&&to.length()!=0)
            {
                //set 'from' to zero
                from="0";
                result=dao.searchByPrice(from, to);
            }
            else if(from.length()!=0&&to.length()!=0)
                result=dao.searchByPrice(from, to);
                
            searchModel.setRowCount(0);
            if(result.size()>0)
            {
                for(PhoneDTO dto:result)
                {
                    searchModel.addRow(dto.toVector());
                }
                lbCountResult.setText(result.size()+" Phone(s)");
            }
            else{
                lbCountResult.setText("No phone satisfy condition!");
            }
        } catch (Exception ex) {
            Logger.getLogger(UserFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    //clear all inputted information
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtPhonename.setText("");
        txtMaker.setText("");
        txtFromPrice.setText("");
        txtToPrice.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void pnlAllPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAllPhoneMouseExited
        try {
            if(linkImage!=null)
                showImage(linkImage,g);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlAllPhoneMouseExited

    private void pnlSearchPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSearchPhoneMouseExited
        try {
            if(linkSearchImage!=null)
                showImage(linkSearchImage,searchG);
        } catch (Exception ex) {
            Logger.getLogger(AdminFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pnlSearchPhoneMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateProfile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbCountResult;
    private javax.swing.JLabel lblRole;
    private javax.swing.JPanel pnlAllPhone;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlPhoneDetail;
    private javax.swing.JPanel pnlPhoneDetail1;
    private javax.swing.JPanel pnlSearchImage;
    private javax.swing.JPanel pnlSearchPhone;
    private javax.swing.JPanel pnlUpdateProfile;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbUser;
    private javax.swing.JTable tblSearchResult;
    private javax.swing.JTable tblView;
    private javax.swing.JLabel txtFailImage;
    private javax.swing.JTextField txtFromPrice;
    private javax.swing.JTextField txtMaker;
    private javax.swing.JTextField txtPhonename;
    private javax.swing.JTextArea txtSearchDescription;
    private javax.swing.JLabel txtSearchFailImage;
    private javax.swing.JTextField txtSearchMaker;
    private javax.swing.JTextField txtSearchPhoneID;
    private javax.swing.JTextField txtSearchPhonename;
    private javax.swing.JTextField txtSearchPrice;
    private javax.swing.JTextArea txtShowDescription;
    private javax.swing.JTextField txtShowMaker;
    private javax.swing.JTextField txtShowPhoneID;
    private javax.swing.JTextField txtShowPhonename;
    private javax.swing.JTextField txtShowPrice;
    private javax.swing.JTextField txtToPrice;
    private javax.swing.JTextField txtUpdateFullname;
    private javax.swing.JPasswordField txtUpdatePassword;
    private javax.swing.JTextField txtUpdateUsername;
    // End of variables declaration//GEN-END:variables
}
